name: Build & Deploy Hugo

on: workflow_dispatch

jobs:
  hugo_build_deploy:
    runs-on: ubuntu-18.04
    steps:
      # Checkout Main Branch
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.PAT_GH_TOKEN }}
          path: thevwj

      # Hugo Stuff
      - name: Temporary Hugo Directory
        run: mkdir /tmp/hugo/

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.59.1"
          extended: true

      # Clone Down Branches
      - name: School Notes Checkout
        uses: actions/checkout@v2
        with:
          repository: B-Vwj/School-Notes
          token: ${{ secrets.PAT_TOKEN }}
          path: school_notes
          ref: master

      # Clean Up Main Site
      - name: Clean-Up
        run: |
          cd thevwj
          cp content/_index.md                  /tmp/hugo/
          cp content/_header.md                 /tmp/hugo/
          cp content/_footer.md                 /tmp/hugo/
          cp -R static/theme-original/          /tmp/hugo/
          rm -rf content/*
          rm -rf public/*
          rm -rf static/*
          cp /tmp/hugo/_index.md                /home/runner/work/TheVwj/TheVwj/thevwj/content/
          cp /tmp/hugo/_header.md               /home/runner/work/TheVwj/TheVwj/thevwj/content/
          cp /tmp/hugo/_footer.md               /home/runner/work/TheVwj/TheVwj/thevwj/content/
          cp -R /tmp/hugo/theme-original        /home/runner/work/TheVwj/TheVwj/thevwj/static/
          cd ..

      # Copy Files
      - name: Pull_School_Notes
        run: |
          cd school_notes
          cp -R school_notes                    /home/runner/work/TheVwj/TheVwj/thevwj/content/

      # Next two stages should always be last
      - name: Prep
        run: |
          cd /home/runner/work/TheVwj/TheVwj/thevwj/
          git fetch origin
          rm -rf public
          mkdir public
          git worktree prune
          rm -rf .git/worktrees/public/
          git worktree add -B gh-pages public origin/gh-pages
          rm -rf public/*
          hugo

      - name: Commit To Master Branch
        run: |
          cd /home/runner/work/TheVwj/TheVwj/thevwj/
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USER }}
          git add .
          git commit -m "GitHub Actions build ${GITHUB_RUN_NUMBER}"

      - name: Deploy To Master Branch 
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: master

      - name: Commit To GH-Pages Branch
        run: |
          cd public 
          git init && git add --all && git commit -m "Publishing To GH-Pages"

      - name: Deploy to GH-Pages Branch
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: gh-pages